/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReplyRouteImport } from './routes/reply'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as EmailRouteImport } from './routes/email'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as IndexRouteImport } from './routes/index'

const ReplyRoute = ReplyRouteImport.update({
  id: '/reply',
  path: '/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/email': typeof EmailRoute
  '/memory': typeof MemoryRoute
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRoute
  '/reply': typeof ReplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/email': typeof EmailRoute
  '/memory': typeof MemoryRoute
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRoute
  '/reply': typeof ReplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/email': typeof EmailRoute
  '/memory': typeof MemoryRoute
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRoute
  '/reply': typeof ReplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/email'
    | '/memory'
    | '/notes'
    | '/planner'
    | '/reply'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coach' | '/email' | '/memory' | '/notes' | '/planner' | '/reply'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/email'
    | '/memory'
    | '/notes'
    | '/planner'
    | '/reply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRoute
  EmailRoute: typeof EmailRoute
  MemoryRoute: typeof MemoryRoute
  NotesRoute: typeof NotesRoute
  PlannerRoute: typeof PlannerRoute
  ReplyRoute: typeof ReplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reply': {
      id: '/reply'
      path: '/reply'
      fullPath: '/reply'
      preLoaderRoute: typeof ReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRoute,
  EmailRoute: EmailRoute,
  MemoryRoute: MemoryRoute,
  NotesRoute: NotesRoute,
  PlannerRoute: PlannerRoute,
  ReplyRoute: ReplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
